### ISSUE TITLE
Make cargo command configurable

### ISSUE THREAD

**Issue by becothas** [mrcjkb/rustaceanvim#305]
### Feature description

When using testables/runnables, they are always executed with cargo. 
There is a tool called `cross-rs` and it has the same interface as cargo. 

Could you make the command to execute testables/runnables configurable?

**Comment by mrcjkb** [comment]
Hmm it sounds reasonable, but it might add some complexity.
I'll look into it 😀
I've already done something like that for cargo-nextest.

**Comment by mrcjkb** [comment]
@becothas I've implemented this in the `cargo-override` branch. Would you mind testing it for me before I merge? :pray:

**Comment by becothas** [comment]
Sure. 

The only thing I found is, that it still shows cargo when selecting the runnables.
 When a runnable is executed, the override is used. 
![image](https://github.com/mrcjkb/rustaceanvim/assets/41289937/5ba837d1-6674-4735-827b-34a1edf80fa4)
Otherwise it works as expected.

**Comment by mrcjkb** [comment]
Thanks! :pray:
